name: Maven Package
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
jobs:
  GuicedInjection:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs: GuicedVertX
    with:
      baseDir: 'GuiceInjection/'
      name: 'Guiced Injection'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedPersistence:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedPersistence/'
      name: 'Guiced Persistence'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedPersistenceC3P0:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedPersistence
    with:
      baseDir: 'GuicedPersistenceC3P0/'
      name: 'Guiced C3P0'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  GuicedServlets:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - GuicedInjection
#    with:
#      baseDir: 'GuicedServlets/'
#      name: 'Guiced Servlets'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#     SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  GuicedWebSockets:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - GuicedServlets
#    with:
#      baseDir: 'GuicedWebSockets/'
#      name: 'Guiced Web Sockets'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  GuicedUndertow:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - GuicedServlets
#    with:
#      baseDir: 'GuicedUndertow/'
#      name: 'Guiced Undertow'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedHazelcast:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedHazelcast/'
      name: 'Guiced Hazelcast'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedHazelcastHibernate:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedHazelcast
    with:
      baseDir: 'GuicedHazelcastHibernate/'
      name: 'Guiced Hazelcast Hibernate'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  GuicedRest:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
##      - GuicedVertX
 #   with:
 #     baseDir: 'GuicedRestServices/'
 #     name: 'Guiced Rest Services'
 #     publishToCentral: ${{inputs.centralRelease}}
 #   secrets:
 #     USERNAME: ${{secrets.USERNAME}}
 #     USER_TOKEN: ${{secrets.USER_TOKEN}}
 #     SONA_USERNAME: ${{secrets.SONA_USERNAME}}
 #     SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
 #     GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
 #     GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  GuicedSessionPerTransaction:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - GuicedServlets
#      - GuicedPersistence
#    with:
#      baseDir: 'GuicedServletsRequestScoping/'
#      name: 'Guiced-Servlet Session Per Transaction'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#  GuicedOpenAPI:
#    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
#    needs:
#      - GuicedRest
#    with:
#      baseDir: 'GuicedSwagger/'
#      name: 'Guiced-Servlet OpenAPI'
#      publishToCentral: ${{inputs.centralRelease}}
#    secrets:
#      USERNAME: ${{secrets.USERNAME}}
#      USER_TOKEN: ${{secrets.USER_TOKEN}}
#      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
#      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
#      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
#      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedSwaggerUI:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedSwaggerUI/'
      name: 'Guiced-Servlet SwaggerUI'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedMicroProfileConfig:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedMicroProfileConfig/'
      name: 'Guiced MicroProfile Config'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedVertX:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
    with:
      baseDir: 'GuicedVertx/'
      name: 'Guiced Vertx'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedVertXSockets:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedVertxSockets/'
      name: 'Guiced Vertx WebSockets'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedVertXSessionPerTransaction:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedVertxSessionPerTransaction/'
      name: 'Guiced Vertx Session-Per-Transaction'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  GuicedRabbit:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedRabbit/'
      name: 'Guiced Rabbit'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}

