name: Maven Package
on:
  workflow_dispatch:
  push:
jobs:
  GuicedInjection:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'GuiceInjection/'
      name: 'Guiced Injection'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  GuicedPersistence:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedPersistence/'
      name: 'Guiced Persistence'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  GuicedServlets:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedInjection
    with:
      baseDir: 'GuicedServlets/'
      name: 'Guiced Servlets'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  GuicedWebSockets:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedServlets
    with:
      baseDir: 'GuicedWebSockets/'
      name: 'Guiced Web Sockets'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
  GuicedUndertow:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - GuicedWebSockets
    with:
      baseDir: 'GuicedUndertow/'
      name: 'Guiced Undertow'
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}